### PR TITLE
Fix clustering limit

### LINKED ISSUE #34: Clustering Bug when Zooming in as close as possible
If you continue zooming in on a tree cluster, it will at some point just show one of the tree-contributions, even if all the tree-contributions have the same location.

E.g.:
Sagar's Yucatán Trees
https://user-images.githubusercontent.com/18365824/107541283-411cc300-6bc7-11eb-9e33-f67ee5f2a483.mp4

E.g.:
Matthias's I don't know where Trees
https://user-images.githubusercontent.com/18365824/107541299-4712a400-6bc7-11eb-92bc-ee7399cefe1f.mp4

### PR DESCRIPTION
**Pull request by sarveshpro**
Fixes #34 

Changes in this pull request:
- add max zoom to map
- increase clustering limit

### CODE REVIEW

File: src/TreeMap/App.svelte [hunk 1]
```diff
@@ -256,99 +257,97 @@
...
-          {:else}
-            <div id="map" class="view" use:createMap />
-          {/if}
+          <div id="map" class="view" use:createMap />
+        {/if}
+      {:else if theme === "light"}
+        <div id="map" class="view" use:createMap />
+      {:else}
+        <div id="map" class="view" use:createMap />
+      {/if}
```
Comment (norbertschuler) [inline src/TreeMap/App.svelte:270]: @sarveshpro Was this done by some automated process of your IDE? Which tool are you using? I'd like to properly format our code, but in this case it does not show the four use cases we have to do for loading the map so clearly anymore as before with 
```javascript
        {#if community === "true"}
           {#if theme === "light"}
            <div id="map" class="view" use:createMap />
           {:else}
             <div id="map" class="view" use:createMap />
           {/if}
        {:else}
          {#if theme === "light"}
           <div id="map" class="view" use:createMap />
          {:else}
            <div id="map" class="view" use:createMap />
          {/if}
        {/if}
```
